# docker-compose.yml文件的版本
version: "3"
# 管理的服务
services:
  redis:
    # 指定镜像
    image: redis:5
    container_name: redis 
    ports:
      # 端口映射
      - 6379:6379
    volumes:
      # 目录映射
      - ./data:/data
    command:
      redis-server

